name = "lune_utils/roxios"
version = "0.1.0"
authors = ["0xJWLabs <hi@0xjwlabs.dev>"]
repository = "https://github.com/lune-utils/roxios"
license = "MIT"

[engines]
lune = "^0.9.4"

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
future = { name = "yetanotherclown/luau_futures", target = "luau", version = "2.0.0-beta.3" }
