name = "lune_utils/roxios"
version = "0.1.0"
authors = ["0xJWLabs <hi@0xjwlabs.dev>"]
repository = "https://github.com/lune-utils/roxios"
license = "MIT"

[engines]
lune = "^0.9.4"

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
futures = { repo = "https://github.com/lune-utils/futures", rev = "6ce822d" }
